name: 'home-server-media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - QBT_WEBUI_ADMIN_USERNAME=admin
      - QBT_WEBUI_ADMIN_PASSWORD=admin
    volumes:
      - C:/Docker Images/qbittorrent:/config
      - G:/Biblioteca/docker_media_downloads/qbittorrent:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - G:/Biblioteca/docker_media_downloads/jackett:/downloads
      - C:/Docker Images/jackett:/config
    ports:
      - '9117:9117'