name: 'home-server-databases'

volumes:
  mariadb_data:
  postgres_data:

networks:
  default:
    name: home-server
    external: true

services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE_ORGANIZR}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
